# Generated by Django 4.2.2 on 2023-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_accounts_delete_guest_tbl_remove_artist_tbl_pasword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist_tbl',
            name='ads',
        ),
        migrations.AddField(
            model_name='artist_tbl',
            name='dob',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist_tbl',
            name='pasword',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist_tbl',
            name='state',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist_tbl',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
